//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class doctorEntities : DbContext
    {
        public doctorEntities()
            : base("name=doctorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dbo_section> dbo_section { get; set; }
        public virtual DbSet<dbo_unuity> dbo_unuity { get; set; }
        public virtual DbSet<registation> registations { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
