//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class registation
    {
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public Nullable<int> sectıon_id { get; set; }
        public Nullable<int> unıty_id { get; set; }
        public Nullable<int> telno { get; set; }
    
        public virtual dbo_section dbo_section { get; set; }
        public virtual dbo_unuity dbo_unuity { get; set; }
    }
}
